"""Build all 20 reference projects into examples/project_portfolio.

The generated directory is intentionally small and self-contained: each project
contains a source fixture, HTML report, PDF, Excel workbook, Power BI PBIP ZIP,
Tableau TWBX/TWB workbook, and the validation metadata needed for a
résumé/demo submission.
"""

from __future__ import annotations

import json
from pathlib import Path

from app.core.projects.catalog import list_project_specs
from app.core.projects.fixtures import build_project_fixture
from app.core.projects.workbench import build_project


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "examples" / "project_portfolio"


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    summaries = []
    for item in list_project_specs():
        project_id = item["id"]
        destination = OUTPUT / project_id
        destination.mkdir(parents=True, exist_ok=True)
        fixture = build_project_fixture(project_id, rows=48)
        fixture.to_csv(destination / "fixture.csv", index=False)
        result = build_project(fixture, project_id=project_id, output_dir=destination)
        summaries.append({
            "project": result["project"],
            "status": result["status"],
            "validation": result["validation"],
            "artifacts": {name: f"{project_id}/{Path(path).name}" for name, path in result["files"].items()},
            "field_mapping": result["analytics"]["field_mapping"],
        })
    (OUTPUT / "validation_results.json").write_text(json.dumps({
        "status": "COMPLETED",
        "count": len(summaries),
        "passed": sum(item["validation"]["valid"] for item in summaries),
        "failed": sum(not item["validation"]["valid"] for item in summaries),
        "projects": summaries,
    }, indent=2), encoding="utf-8")
    (OUTPUT / "README.md").write_text(
        "# Portfolio project validation\n\n"
        "This directory contains the deterministic 48-row fixtures and source-backed BI artifacts generated by `scripts/build_project_portfolio.py`.\n\n"
        "Every project is rendered with its catalogued dashboard template and validated for a collision-free layout, at least two KPIs, two charts, one table, HTML/PDF/XLSX generation, a Power BI PBIP project bundle, and Tableau TWBX/TWB workbooks. Power BI projects use the integrated `powerbi_executive_sales`, `powerbi_ecommerce_conversion`, or `powerbi_kpi_slicer` reference templates. Extract a `report.pbip.zip` before opening the `.pbip` shortcut in Power BI Desktop (PBIP preview), or open `report.twbx` in Tableau Desktop/Reader.\n",
        encoding="utf-8",
    )
    print(f"Built {len(summaries)} projects: {sum(item['validation']['valid'] for item in summaries)} passed")


if __name__ == "__main__":
    main()
