from enum import StrEnum


class DeliveryBasis(StrEnum):
    FOB = "FOB"
    DES = "DES"
    DELIVERED_TERMINAL = "DELIVERED_TERMINAL"
    CONTRACT_DEFINED = "CONTRACT_DEFINED"


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    PUBLIC_CLAIM = "PUBLIC_CLAIM"
    INDICATIVE = "INDICATIVE"
    INFERRED = "INFERRED"
    ESTIMATED = "ESTIMATED"
    STALE = "STALE"
    UNVERIFIED = "UNVERIFIED"


class TransactionType(StrEnum):
    SPOT = "SPOT"
    STRIP = "STRIP"
    SHORT_TERM = "SHORT_TERM"
    TERM = "TERM"


class RFQStatus(StrEnum):
    NEW = "NEW"
    QUALIFYING = "QUALIFYING"
    SOURCING = "SOURCING"
    SELLER_SHORTLIST = "SELLER_SHORTLIST"
    PRICING = "PRICING"
    SHIPPING_ANALYSIS = "SHIPPING_ANALYSIS"
    QUOTING = "QUOTING"
    NEGOTIATING = "NEGOTIATING"
    CREDIT_REVIEW = "CREDIT_REVIEW"
    CONTRACTING = "CONTRACTING"
    CONFIRMED = "CONFIRMED"
    LOST = "LOST"
    ON_HOLD = "ON_HOLD"
    CANCELLED = "CANCELLED"


class CargoStatus(StrEnum):
    INDICATIVE = "INDICATIVE"
    AVAILABLE = "AVAILABLE"
    OFFERED = "OFFERED"
    OPTIONED = "OPTIONED"
    MATCHED = "MATCHED"
    CONFIRMED = "CONFIRMED"
    LOADING_SCHEDULED = "LOADING_SCHEDULED"
    IN_TRANSIT = "IN_TRANSIT"
    DISCHARGING = "DISCHARGING"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"


class CompatibilityStatus(StrEnum):
    PASS = "PASS"
    WARNING = "WARNING"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"


class TerminalCompatibility(StrEnum):
    COMPATIBLE = "COMPATIBLE"
    CONDITIONALLY_COMPATIBLE = "CONDITIONALLY_COMPATIBLE"
    INCOMPATIBLE = "INCOMPATIBLE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class ProjectStatus(StrEnum):
    PROPOSED = "PROPOSED"
    FID_PENDING = "FID_PENDING"
    UNDER_CONSTRUCTION = "UNDER_CONSTRUCTION"
    COMMISSIONING = "COMMISSIONING"
    OPERATING = "OPERATING"
    EXPANSION = "EXPANSION"
    DELAYED = "DELAYED"
    SUSPENDED = "SUSPENDED"
    CANCELLED = "CANCELLED"


class ComplianceStatus(StrEnum):
    CLEAR = "CLEAR"
    REVIEW_REQUIRED = "REVIEW REQUIRED"
    BLOCKED = "BLOCKED"
    INSUFFICIENT_DATA = "INSUFFICIENT DATA"


class ConversionBasis(StrEnum):
    ACTUAL_CARGO_VALUE = "ACTUAL_CARGO_VALUE"
    CONTRACT_ASSUMPTION = "CONTRACT_ASSUMPTION"
    STANDARD_ESTIMATE = "STANDARD_ESTIMATE"
